version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 879344392617.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t traveldoo-hotel-image-repo:latest .
      - docker tag traveldoo-hotel-image-repo:latest 879344392617.dkr.ecr.ap-northeast-1.amazonaws.com/traveldoo-hotel-image-repo:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 879344392617.dkr.ecr.ap-northeast-1.amazonaws.com/traveldoo-hotel-image-repo:latest
